version: '3.2'

services:
  sugu-ms-tango:
    build: ./
    container_name: sugu-ms-tango
    ports:
      - 3004:3004
    env_file:
      - ./.env.docker
    volumes:
      - node_modules:/ms-tango/api/node_modules
    command: npm run start:dev
    networks:
      - uea-core-api_sugu_network
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /ms-tango/api/src
          ignore:
            - node_modules/

volumes:
  node_modules:
    driver: "local"
  
networks:
  uea-core-api_sugu_network:
    external: true

#test